### ISSUE TITLE
Setup Reactjs

### ISSUE THREAD

**Issue by AbdourahamaneIssakaSani** [F38STUDIO/site-f38-studio#1]
- [x] Créer une nouvelle branche
- [x] Sur cette branche, remove tous les fichier et dossiers ( `css`, `js`, `pages`, `index.html` )
- [x] Générer un projet react avec la commande `create-react-app . `
- [x] Push, raise a Pull Request (PR) and request a review

**Comment by AbdourahamaneIssakaSani** [comment]
@LeGrandF38 check here

**Comment by LeGrandF38** [comment]
hi

**Comment by AbdourahamaneIssakaSani** [comment]
test automated notif

**Comment by AbdourahamaneIssakaSani** [comment]
Hello @LeGrandF38 , click sur Pull Requests and crée une concernant ta branche.
